# Transformation

In [1]:
import numpy as np

## Translation

In [5]:
point = np.array([[1], [2]])
print(point)

[[1]
 [2]]


## Rotation

In [17]:
phi = 45*np.pi/180

R_z = np.array([[np.cos(phi), -np.sin(phi)],  
                [np.sin(phi),  np.cos(phi)]])
print(R_z)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [16]:
np.matmul(R_z, point)

array([[-0.70710678],
       [ 2.12132034]])

# Image Transformation

In [1]:
text


NameError: name 'text' is not defined

## Scaling

Shearing